# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
logging:
  level: INFO

imageDefaults:
  registry: docker.io
  namespace: odpi
  tag: latest
  pullPolicy: IfNotPresent

egeria:
  user: myuser
  cohort: coco
  server: myserver

image:
  egeria:
    name: egeria
    pullPolicy: Always

  configure:
    name: egeria-configure
    pullPolicy: Always

crux:
  version: 21.05-1.17.0-beta
  connectorversion: "2.10"
  connectorurl: "http://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=org.odpi.egeria&a=egeria-connector-crux&v=RELEASE&c=jar-with-dependencies"
  proxyserver: crux

records: 5

rocksdb:
  version: 6.15.2

jnr:
  version: 2.2.1

kafka:
  zookeeper:
    persistence:
      enabled: false
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - cr5
            topologyKey: "kubernetes.io/hostname"
  persistence:
    enabled: false
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - cr5
          topologyKey: "kubernetes.io/hostname"
...
