# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
logging:
  level: INFO

imageDefaults:
  registry: docker.io
  namespace: odpi
  tag: latest
  pullPolicy: IfNotPresent

egeria:
  user: myuser
  cohort: coco
  server: myserver

release:
  version: 2.7-SNAPSHOT
  repo: snapshot

image:
  egeria:
    name: egeria
    pullPolicy: Always

  configure:
    name: egeria-configure
    pullPolicy: Always

crux:
  version: 21.01-1.14.0-beta
  connectorversion: 1.0-SNAPSHOT
  snapshotversion: 1.0-20210216.011013-9
  snapshottoken: ""
  proxyserver: crux

records: 5

rocksdb:
  version: 6.15.2

jnr:
  version: 2.2.1

kafka:
  securityContext:
    enabled: false
  zookeeper:
    persistence:
      enabled: false
  persistence:
    enabled: false
