# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
name: ec-pts-graph
description: ODPi Egeria PTS automation for the Graph connector
apiVersion: v1
version: 0.1
icon: https://raw.githubusercontent.com/odpi/egeria/99016e77167fa30dcfade809b061358a92a59973/assets/img/egeria.png
keywords:
  - odpi, egeria, open-metadata, connector, cts, graph, janus
sources:
  - https://github.com/odpi/egeria-connector-janusgraph
home: https://github.com/odpi/egeria-connector-janusgraph
maintainers:
  - name: Christopher Grote
    email: chris@thegrotes.net
