# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
logging:
  level: INFO

imageDefaults:
  registry: docker.io
  namespace: odpi
  tag: latest
  pullPolicy: IfNotPresent

egeria:
  user: myuser
  cohort: coco
  server: myserver

image:
  egeria:
    name: egeria
    pullPolicy: Always

  configure:
    name: egeria-configure
    pullPolicy: Always

records: 5

volumeParameters:
  instancesPerType: 5
  maxSearchResults: 2
  waitBetweenScenarios: 0
  profilesToSkip: "[]"

kafka:
  zookeeper:
    persistence:
      enabled: false
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - g5-2
            topologyKey: "kubernetes.io/hostname"
  persistence:
    enabled: false
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - g5-2
          topologyKey: "kubernetes.io/hostname"
...
