# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the ODPi Egeria project.

site_name: Crux Plugin Repository Connector
site_description: Pluggable repository for Egeria, with native support for historical metadata.
copyright: "License: <a href='https://creativecommons.org/licenses/by/4.0/'>CC BY 4.0</a>, &copy; 2018-2021 contributors to the Egeria project."
repo_name: odpi/egeria-connector-crux
repo_url: https://github.com/odpi/egeria-connector-crux
site_url: https://odpi.github.io/egeria-connector-crux/
edit_uri: ""

nav:
  - About: index.md
  - Getting started:
      - getting-started/setup.md
      - getting-started/explore.md
  - How it works: how-it-works.md
  - Conformance:
      - cts/testing-overview.md
      - cts/2.11/2.11.md
      - cts/2.10/2.10.md
      - cts/2.9/2.9.md
      - cts/2.8/2.8.md
  - Migration:
      - migrating/how-migration-works.md
      - migrating/run-migration.md
      - migrating/build-migrator.md
  - High availability:
      - high-availability/sample.md
      - high-availability/limitations.md

theme:
  name: material
  language: en
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
#    - navigation.instant
    - navigation.top
#    - toc.integrate
  palette:
    - scheme: default
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  logo: assets/images/egeria-header.png

extra_css:
  - assets/stylesheets/egeria.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/odpi/egeria
      name: Egeria on GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/odpi
      name: Egeria on Docker
    - icon: fontawesome/brands/medium
      link: https://medium.com/tag/egeria
      name: Egeria on Medium
    - icon: fontawesome/brands/slack
      link: https://lfaifoundation.slack.com/archives/C01F40J2XA8
      name: Egeria on Slack

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
