# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
logging:
  level: INFO

imageDefaults:
  registry: docker.io
  namespace: odpi
  tag: latest
  pullPolicy: IfNotPresent

egeria:
  user: myuser
  cohort: coco
  server: myserver

image:
  egeria:
    name: egeria
    pullPolicy: IfNotPresent

  configure:
    name: egeria-configure
    pullPolicy: IfNotPresent

crux:
  version: 1.18.1
  connectorversion: "3.0"
  connectorurl: "http://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=org.odpi.egeria&a=egeria-connector-crux&v=RELEASE&c=jar-with-dependencies"
  proxyserver: crux
  replicaCount: 2

volumeParameters:
  instancesPerType: 5
  maxSearchResults: 2
  waitBetweenScenarios: 0
  profilesToSkip: "[]"

dependencyVersions:
  rocksdb: 6.15.2
  jnr: 2.2.1
  kafka: 2.8.0
  postgres: 42.2.18

jdbcDetails:
  service: edb-crux-any
  secret: edb-crux-superuser

kafka:
  replicaCount: 2
  persistence:
    enabled: false
  zookeeper:
    persistence:
      enabled: false
...
