# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
logging:
  level: WARN

imageDefaults:
  registry: docker.io
  namespace: odpi
  tag: latest
  pullPolicy: IfNotPresent

egeria:
  user: myuser
  cohort: coco
  server: myserver

image:
  egeria:
    name: egeria
    pullPolicy: Always

  configure:
    name: egeria-configure
    pullPolicy: Always

xtdb:
  version: 1.19.0-beta1
  connectorversion: "3.2"
  connectorurl: "http://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=org.odpi.egeria&a=egeria-connector-xtdb&v=RELEASE&c=jar-with-dependencies"
  proxyserver: xtdb

volumeParameters:
  instancesPerType: 5
  maxSearchResults: 2
  waitBetweenScenarios: 0
  profilesToSkip: "[]"

kafka:
  zookeeper:
    persistence:
      enabled: false
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - c5-2
            topologyKey: "kubernetes.io/hostname"
  persistence:
    enabled: false
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - c5-2
          topologyKey: "kubernetes.io/hostname"
...
